### PR TITLE
Add cycles

### PR DESCRIPTION
**Pull request by qadzek**
- Cardinal directions
- Orientations
- NATO phonetic alphabet

### CODE REVIEW

**Comment by Konfekt** [comment]
Thank you very much. I'll remove `November` from the Nato list, as I suspect it to be more commonly used to cycle among months.

**Comment by qadzek** [comment]
> Thank you very much. I'll remove November from the Nato list, as I suspect it to be more commonly used to cycle among months.

Good call. I didn't really check for conflicts with existing cycles.

**Comment by qadzek** [comment]
Apologies, I discovered another conflict in the NATO list: `delta` and the Greek alphabet. `echo` might also cause issues in e.g. `*.vim` files.

I am not sure what the best way forward is: remove these conflicting NATO letters or scrap the entire NATO alphabet.

**Comment by Konfekt** [comment]
Good catch, echo seems fine, but removing delta seems sensible.

**Comment by Konfekt** [comment]
Just removed it. There's the third option of leaving it, when it switches to greek starting from delta, but that's rather confusing.

**Comment by qadzek** [comment]
The plugin throws `E15: Invalid expression`, because `'delta'` was removed in the last commit, but its comma wasn't.

**Comment by Konfekt** [comment]
Should be fixed

**Pull request merged**
